#:schema node_modules/wrangler/config-schema.json
name = "custom-hostname-jldec-net"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "*/*", zone_name = "jldec.net" }
]

[observability]
enabled = true
